// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjgtvcawfbvmalmyekiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqZ3R2Y2F3ZmJ2bWFsbXlla2l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDI2OTEsImV4cCI6MjA3MjY3ODY5MX0.K1xqrF2MzIxNn50J85GmlPRThFeE--c2KE6t2k86q5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});